<script setup lang="ts">
import { useAuth } from '~/modules/auth'

const { t } = useI18n()
const localePath = useLocalePath()

useSeoMeta({ title: t('auth.seoTitle') })

const route = useRoute()
const { isLoggedIn, login } = useAuth()

// Already authenticated (e.g. link reopened after login): no point showing
// the form again, go where you would have gone anyway.
if (isLoggedIn.value) {
  const target =
    typeof route.query.redirectTo === 'string' ? route.query.redirectTo : localePath('/')
  await navigateTo(target)
}

const username = ref('')
const password = ref('')
const error = ref<string | null>(null)
const loading = ref(false)

async function submit() {
  error.value = null
  loading.value = true
  try {
    await login(username.value, password.value)
    const target =
      typeof route.query.redirectTo === 'string' ? route.query.redirectTo : localePath('/')
    await navigateTo(target)
  } catch {
    error.value = t('auth.loginError')
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <v-container class="py-8 d-flex justify-center">
    <v-card max-width="400" width="100%">
      <v-card-item>
        <v-card-title>
          <h1 class="text-h5 ma-0">{{ t('auth.login') }}</h1>
        </v-card-title>
        <v-card-subtitle>{{ t('auth.loginSubtitle') }}</v-card-subtitle>
      </v-card-item>
      <v-card-text>
        <v-alert v-if="error" type="error" class="mb-4" :text="error" />
        <!--
          `type="button"` + `@click`/`@keydown.enter`, not `@submit.prevent`
          on `v-form`: internally Vuetify, after validation, calls
          `formRef.value.submit()` — a REAL native submit of the underlying
          HTML `<form>`, which ignores any earlier `preventDefault()` (it is
          not generated by an event, there is nothing to prevent). Real
          result observed with a real browser (Playwright): a native page
          reload right after login, before `navigateTo` managed to take the
          user to the destination page — not a problem visible with `curl`,
          only with a real interaction.
        -->
        <v-form>
          <v-text-field
            v-model="username"
            :label="t('auth.username')"
            autocomplete="username"
            class="mb-2"
            @keydown.enter="submit"
          />
          <v-text-field
            v-model="password"
            type="password"
            :label="t('auth.password')"
            autocomplete="current-password"
            class="mb-4"
            @keydown.enter="submit"
          />
          <v-btn
            type="button"
            color="primary"
            variant="flat"
            block
            :loading="loading"
            @click="submit"
          >
            {{ t('auth.login') }}
          </v-btn>
        </v-form>
      </v-card-text>
    </v-card>
  </v-container>
</template>
