/**
 * A completed charging session, non-OCM data (like `StationTelemetry`,
 * `shared/schemas/telemetry.ts`): OCM has no concept of a session, only the
 * station registry. Generated by the simulator, see
 * server/services/session-simulator.ts.
 */
export interface ChargingSession {
  id: string
  stationId: number
  stationName: string
  connectorId: number
  connectorType: string
  /** ISO 8601. */
  startedAt: string
  /** ISO 8601. */
  endedAt: string
  durationMinutes: number
  energyKwh: number
  averagePowerKw: number
  peakPowerKw: number
  costEur: number
}
